* header

Neque amet architecto occaecati delectus sint qui aut. Beatae vel
omnis quis voluptas aperiam facere ea. Unde ratione molestiae
necessitatibus nisi voluptatem.

=rplacd #!false=

~rplacd #!false~

=set! \= assignment=

~set! \~ assignment~

** header

Sed eum quas ad. Qui praesentium et dolorem inventore nam rerum.
Eum temporibus amet fugit consequatur optio. Ratione beatae
tenetur animi et dolores.

Dolores ipsum vero molestiae impedit corporis amet. Deserunt sed
reiciendis est. Cumque ab tenetur in odit beatae ad.

#+BEGIN_VERSE
roses are red
violets are blue
most poems rhyme
this one doesn't

roses are red
violets are blue
most poems rhyme
this one doesn't
#+END_VERSE

Sint nemo nisi quo. Autem ipsum quaerat quia. Ut consectetur
tempora sed.

#+BEGIN_SRC
(define factorial
  (lambda (n)
    (if (= n 0)
        1
        (* n (factorial (- n 1))))))

(define factorial
  (lambda (n)
    (if (= n 0)
        1
        (* n (factorial (- n 1))))))
#+END_SRC

Corporis aut nisi ipsum est autem et reprehenderit quia. Veniam
autem veniam dolorem delectus rem sunt. Illum accusamus
exercitationem et dolorem. Ut autem reiciendis voluptatum ut eos
atque. Rem quidem in omnis modi.
#+

Impedit aliquam doloremque libero aspernatur sequi officiis
veniam. Modi quidem et sed est. A doloremque sunt ipsam sint
recusandae omnis tempora. Rem voluptatem consequatur quo
veritatis nihil.

Sit debitis quasi sequi necessitatibus eos dolorem. Hic rerum
error fugit ipsum facere doloremque facilis. Sed ut minus odit
fugit repellendus itaque dolor earum. Sed libero minus
reprehenderit ut similique deleniti perferendis.

Quisquam quas maiores voluptas eligendi reiciendis. Voluptates
consequatur est minus vero rerum quis. Officia aut ut sapiente
sit possimus placeat fugiat. Debitis ea nostrum unde.

Consequatur explicabo pariatur sint enim quia dolor. Sed
quibusdam rerum velit facilis iste enim voluptatem. Qui nulla
vitae eligendi est sequi ut perspiciatis. Laboriosam recusandae
distinctio reprehenderit dolores ea voluptatibus.
